# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-25 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gstudent',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('intro', models.CharField(max_length=500)),
                ('bio', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='staff',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('intro', models.CharField(max_length=500)),
                ('bio', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ustudent',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('intro', models.CharField(max_length=500)),
                ('bio', models.TextField()),
            ],
        ),
    ]
