# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-18 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('title', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='indexContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', models.TextField(null=True)),
                ('text2', models.TextField(null=True)),
                ('text3', models.TextField(null=True)),
                ('pics1', models.ImageField(upload_to='Aimg')),
                ('pics2', models.ImageField(upload_to='Aimg')),
                ('pics3', models.ImageField(upload_to='Aimg')),
            ],
        ),
        migrations.CreateModel(
            name='papers',
            fields=[
                ('title', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('year', models.IntegerField(default=2017)),
                ('file', models.FileField(upload_to='file')),
            ],
        ),
        migrations.RemoveField(
            model_name='gstudent',
            name='intro',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='intro',
        ),
        migrations.RemoveField(
            model_name='ustudent',
            name='intro',
        ),
        migrations.AddField(
            model_name='gstudent',
            name='researchInterest',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='courses',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='publications',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='researchInterest',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ustudent',
            name='researchInterest',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='gstudent',
            name='bio',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='bio',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='ustudent',
            name='bio',
            field=models.TextField(null=True),
        ),
    ]
