# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-27 12:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('IMS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.TextField()),
                ('Email', models.EmailField(max_length=254)),
            ],
            options={
                'ordering': ['-date_time'],
            },
        ),
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.TextField()),
            ],
            options={
                'ordering': ['-date_time'],
            },
        ),
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='indexContent',
            fields=[
                ('name', models.CharField(default='indexContent', max_length=100, primary_key=True, serialize=False)),
                ('title1', models.CharField(default='About', max_length=100)),
                ('text1', models.TextField(null=True)),
                ('text2', models.TextField(null=True)),
                ('text3', models.TextField(null=True)),
                ('pics1', models.ImageField(default='Aimg/no-img.jpg', upload_to='Aimg')),
                ('pics2', models.ImageField(default='Aimg/no-img.jpg', upload_to='Aimg')),
                ('pics3', models.ImageField(default='Aimg/no-img.jpg', upload_to='Aimg')),
            ],
        ),
        migrations.CreateModel(
            name='papers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=50)),
                ('year', models.IntegerField(default=2017)),
                ('file', models.FileField(upload_to='PFile')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-date_time'],
            },
        ),
        migrations.CreateModel(
            name='patent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.TextField()),
            ],
            options={
                'ordering': ['-date_time'],
            },
        ),
        migrations.CreateModel(
            name='resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('file', models.FileField(upload_to='RFile')),
            ],
            options={
                'ordering': ['-date_time'],
            },
        ),
        migrations.RemoveField(
            model_name='gstudent',
            name='intro',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='intro',
        ),
        migrations.RemoveField(
            model_name='ustudent',
            name='intro',
        ),
        migrations.AddField(
            model_name='gstudent',
            name='img',
            field=models.ImageField(default='Simg/no-img.jpg', upload_to='Simg'),
        ),
        migrations.AddField(
            model_name='gstudent',
            name='researchInterest',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='courses',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='img',
            field=models.ImageField(default='Simg/no-img.jpg', upload_to='Simg'),
        ),
        migrations.AddField(
            model_name='staff',
            name='publications',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='researchInterest',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ustudent',
            name='img',
            field=models.ImageField(default='Simg/no-img.jpg', upload_to='Simg'),
        ),
        migrations.AddField(
            model_name='ustudent',
            name='researchInterest',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='gstudent',
            name='bio',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='bio',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='ustudent',
            name='bio',
            field=models.TextField(null=True),
        ),
    ]
