# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-18 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMS', '0002_auto_20171018_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='gstudent',
            name='img',
            field=models.ImageField(default='Simg/no-img.jpg', upload_to='Simg'),
        ),
        migrations.AddField(
            model_name='staff',
            name='img',
            field=models.ImageField(default='Simg/no-img.jpg', upload_to='Simg'),
        ),
        migrations.AddField(
            model_name='ustudent',
            name='img',
            field=models.ImageField(default='Simg/no-img.jpg', upload_to='Simg'),
        ),
        migrations.AlterField(
            model_name='indexcontent',
            name='pics1',
            field=models.ImageField(default='Aimg/no-img.jpg', upload_to='Aimg'),
        ),
        migrations.AlterField(
            model_name='indexcontent',
            name='pics2',
            field=models.ImageField(default='Aimg/no-img.jpg', upload_to='Aimg'),
        ),
        migrations.AlterField(
            model_name='indexcontent',
            name='pics3',
            field=models.ImageField(default='Aimg/no-img.jpg', upload_to='Aimg'),
        ),
    ]
