# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-18 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMS', '0003_auto_20171018_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gstudent',
            name='img',
            field=models.ImageField(default='static/Simg/no-img.jpg', upload_to='static/Simg'),
        ),
        migrations.AlterField(
            model_name='indexcontent',
            name='pics1',
            field=models.ImageField(default='static/Aimg/no-img.jpg', upload_to='static/Aimg'),
        ),
        migrations.AlterField(
            model_name='indexcontent',
            name='pics2',
            field=models.ImageField(default='static/Aimg/no-img.jpg', upload_to='static/Aimg'),
        ),
        migrations.AlterField(
            model_name='indexcontent',
            name='pics3',
            field=models.ImageField(default='static/Aimg/no-img.jpg', upload_to='static/Aimg'),
        ),
        migrations.AlterField(
            model_name='papers',
            name='file',
            field=models.FileField(upload_to='static/file'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='img',
            field=models.ImageField(default='static/Simg/no-img.jpg', upload_to='static/Simg'),
        ),
        migrations.AlterField(
            model_name='ustudent',
            name='img',
            field=models.ImageField(default='static/Simg/no-img.jpg', upload_to='static/Simg'),
        ),
    ]
