# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-18 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMS', '0006_auto_20171018_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexcontent',
            name='id',
        ),
        migrations.AddField(
            model_name='indexcontent',
            name='name',
            field=models.CharField(default='indexContent', max_length=100, primary_key=True, serialize=False),
        ),
    ]
