# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-18 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMS', '0007_auto_20171018_2312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='papers',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='blog',
            name='date_time',
        ),
        migrations.AddField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='papers',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
