# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-18 16:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IMS', '0009_auto_20171019_0003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-date_time']},
        ),
        migrations.AlterModelOptions(
            name='papers',
            options={'ordering': ['-date_time']},
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='date',
            new_name='date_time',
        ),
        migrations.RenameField(
            model_name='papers',
            old_name='date',
            new_name='date_time',
        ),
    ]
