# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-19 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMS', '0010_auto_20171019_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='papers',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='papers',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
