# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-24 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMS', '0014_auto_20171024_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='ask',
            options={'ordering': ['-date_time']},
        ),
        migrations.AlterModelOptions(
            name='patent',
            options={'ordering': ['-date_time']},
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ['-date_time']},
        ),
    ]
