# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-24 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMS', '0015_auto_20171024_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='ask',
            name='Email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='ask',
            name='date_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='date_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='papers',
            name='date_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='patent',
            name='date_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='date_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
