# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-24 14:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('IMS', '0016_auto_20171024_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ask',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='papers',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='patent',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
